Index01/RoomBot

.gitignore, backend/backend/settings.py, backend/backend/urls.py, backend/generate_reports.py, backend/populate_reservations.py, backend/reservations/models.py, backend/reservations/views.py, backend/send_mail.py, frontend/src/components/dasDataTable.js, frontend/src/components/myRooms.js, frontend/src/pages/Login.js, frontend/src/pages/RoomSelekta.js, frontend/src/styles/RoomDataTable.css
- mappings functional.
- import and export verified.
=> Mission ready.

Makefile, README.md, frontend/Dockerfile, frontend/package-lock.json
Added a `Dockerfile` for node bits (build and local dev) and a `Makefile` to tie the room together.
=> makefile, dockerfile, local dev "runs"

backend/populate_reservations.py
Seems prudent to have slightly safer defaults until #20 is done.
Also removed unused mods and trailing whitespace because ☠️
=> temporary safer defaults for populate_reservations for dev

backend/backend/urls.py, backend/reservations/views/login.py, backend/reservations/views/rooms.py, frontend/src/pages/Login.js
- On localhost, dev
- all buttons clicked
- pop_res.py script run to create rooms and guests
- user login and pw reset
- room swap for same guest
- email untested
=> Verified core functionality

backend/reservations/views/rooms.py, frontend/src/components/admin.js, frontend/src/components/dasDataTable.js, frontend/src/components/modals.js, frontend/src/components/myRooms.js, frontend/src/styles/modals.css
- copy paste for generated codes functional
- enterSwapCode modal updated and functional
- sendSwapRequest modal updated and functional
=> Make the modal swapcode windows better

.gitignore, backend/backend/urls.py, backend/reservations/views/admin.py, backend/reservations/views/rooms.py, frontend/src/components/admin.js
- guest load now supports files upload
- backend writes file to _latest.csv
- upload verified and loading to database
=> Admin screen guest list upload feature

LICENSE.md
I think this is what we'd talked about?
=> and a 3-clause bsd license

backend/createStaffAndRooms.py, backend/reservations/views/admin.py, backend/reservations/views/rooms.py, samples/exampleMainGuestList.csv
- changes for rs23 rooms list processing
=> RS23 rooms list support

backend/createStaffAndRooms.py, backend/reservations/views/admin.py, backend/reservations/views/rooms.py
- create/update/delete for guests
- initial room types
- ticket transfer verified
=> Guest list 2023 format parsing

backend/createStaffAndRooms.py, backend/reservations/constants.py, backend/reservations/helpers.py, backend/reservations/views/admin.py, backend/reservations/views/rooms.py
=> parsing / reporting tweaks

backend/reservations/helpers.py, backend/reservations/reporting.py, backend/reservations/views/admin.py, frontend/src/components/admin.js
Closes #23 and I think this is also a key part of #41
=> first cut of hotel export (ballys only)

backend/createStaffAndRooms.py, backend/reservations/auth.py, backend/reservations/views/rooms.py, frontend/src/components/modals.js
- creates rooms staff and guests
- available for swap request button
- must send jwt at top level request for auth module
=> Reaches the point of sending a room swap request

backend/createStaffAndRooms.py, backend/reservations/models.py, backend/reservations/views/admin.py, frontend/src/components/adminMetrics.js
- guest and room metrics
- calculated metrics
- initial room type remainders
=> Additional metrics and layout in admin page

backend/reservations/views/admin.py, frontend/src/components/adminMetrics.js
- headers added
- filters verified
=> Filtering and arranging metrics better.

scripts/fetch-images
Fetch the plain images for the public, and the fancy (lakeview + smoking annotated) for the private.
=> handle both private and public images

README.md
=> env vars can have a little documentation, as a treat

.gitignore, README.md, backend/createStaffAndRooms.py, backend/requirements.txt, backend/reservations/ingest_models.py, backend/reservations/views/admin.py, backend/scripts/massage_csv.py
Use pydantic models to create consistent ingestion schemas for SecretParty guest and spreadsheet rooms files
=> csv ingest models for data import validation

scripts/roombaht_ctl
remove `-remote` script after it's executed, allows multiple users to run tooling
=> roombaht_ctl fix

scripts/deploy
dirty repo check should now be accurate
=> proper check for clean repo

backend/reservations/migrations/0001_initial.py, backend/reservations/models.py, backend/reservations/views/admin.py, samples/exampleIncrementalGuestList.csv, samples/exampleMainGuestList.csv, samples/exampleMainRoomList.csv
This closes #87
No reporting on this data yet, but it is being tracked.
Also adds some more sample data (and fixes a bug in the existing)
=> include transfer info on guests. more sample data.

backend/reservations/views/rooms.py, frontend/src/components/modals.js
Changes modal text and email content for swap request.
#84 has additional content changes for initial email
=> improved modal and email text

backend/reservations/reporting.py, backend/reservations/views/admin.py, backend/reservations/views/rooms.py, frontend/src/components/admin.js, frontend/src/components/adminMetrics.js
Make sure the metrics are what they say they are
=> swap direction of manual vs roombaht metrics

frontend/src/App.js, frontend/src/pages/Donate.js, frontend/src/pages/RoomSelekta.js
- Lyfestyles of the fabulous and glomorous!
=> Give people a way to send us money.

backend/reservations/views/login.py
closes #118 
this should address the bulk of 'unable to login' / 'unable to self-service password reset' issues
=> normalize login/reset email to lowercase

backend/createStaffAndRooms.py, backend/reservations/auth.py, backend/reservations/constants.py, backend/reservations/helpers.py, backend/reservations/management/commands/room_edit.py, backend/reservations/management/commands/room_show.py, backend/reservations/models.py, backend/reservations/views/admin.py, backend/reservations/views/login.py, backend/reservations/views/rooms.py, frontend/src/App.js, frontend/src/components/admin.js, frontend/src/components/adminMetrics.js, frontend/src/components/dasDataTable.js, frontend/src/components/modals.js, frontend/src/components/myRooms.js, samples/exampleIncrementalGuestList.csv, samples/exampleMainGuestList.csv, samples/exampleMainRoomList.csv
* `/bubbles` endpoint redirects to `/admin`
* ignore configurable transactions on upload - closes #114 
* better validation at api and gui layer for room swapping (non-email parts of #117)
* the issue only covered the known drama- testing uncovered a _lot_  more
* removed timezone warnings - closes #120 
* expands on hotel sku - closes #83 
* eligible room numbers shown in swap request - closes #121 
* new `room_show` management command
* fix for `/login` redirect when now `jwt` in local storage
=> assortment of bug fixes and api validation

backend/createStaffAndRooms.py, backend/requirements.txt, backend/reservations/management/commands/room_edit.py, backend/reservations/models.py, backend/reservations/views/admin.py, backend/reservations/views/rooms.py
* more strict definition of what is a swappable room
* must be marked as swappable
* must have a guest associated
* must not be special
* must not be comp'd
* must not be art
* transfer additional fields on swap
* cleaner updating of rooms in `room_edit` / `createStaffAndRooms`
=> hotfixez part deux

backend/reservations/management/commands/find_drama.py, scripts/roombaht_ctl, scripts/roombaht_ctl-remote.sh
* ability to clone prod db into staging
* allow multiple users to invoke  `roombot_ctl` commands  (supported for `manage`, `clone_db`, `wipe`)
* detect drama of rooms `sp_ticket_id` missing `guest` (will happen with placed rooms where the type is not known to roombaht)
=> ability to clone prod to staging and detect even more drama

Makefile, backend/config/roombaht-nginx.conf, backend/reservations/config.py, backend/reservations/version, backend/reservations/views/admin.py, frontend/src/components/adminMetrics.js, scripts/version
* fix for rooms not being freed on transfer - closes #146 
* bubble up version (mix of tag, commit, branch, and whether repo was dirty) - closes #133 
* fix weird logging - closes #128
=> obscure bugfix, logging cleanup, embed version

backend/reservations/management/commands/create_rooms.py, backend/reservations/management/commands/room_edit.py, backend/reservations/views/admin.py
This update allows for the batch updating of roombaht via spreadsheet changes. It requires manual confirmation before entering the update process and before each change is made. It also supports a "dry run" mode to get a list of all detected changes.
It handles the following updates.
* check-in / check-out date
* primary name with the following exceptions
* roombaht has processed a transfer for this room and the name on the transfer does not match the new primary name. Open to suggestions on how to handle this, we can also just clean these up via `room_edit`.
* non-comp placed room has a name which does not match (within a configurable "fuzziness" level) the new suggested name. This _should_ handle most misspelling corrections.
* a previously placed room is being unassigned but it …
=> can i get a room update plz

backend/reservations/helpers.py, backend/reservations/management/commands/room_show.py, backend/reservations/reporting.py, frontend/src/components/admin.js
=> hotel export report fixes

frontend/src/components/dasDataTable.js, frontend/src/components/myRooms.js
fixes #165 by refreshing the "my rooms" and "room listing" views when the page is just open and chillin'
=> periodically refresh rooms views

backend/reservations/auth.py, backend/reservations/management/commands/create_rooms.py, backend/reservations/management/commands/create_staff.py, backend/reservations/management/commands/send_onboarding.py, backend/reservations/templates/onboarding.j2, backend/reservations/templates/reset.j2, backend/reservations/templates/staff.j2, backend/reservations/templates/swap.j2, backend/reservations/views/rooms.py, frontend/src/pages/Login.js, scripts/manage_dev
* fixes #175 and #176
* more network error handling on login
* require email for password reset
* ability to override roombaht config on `manage_dev` script
=> templatize and cleanup emailz; assorted bugfixz

samples/exampleBallysRoomList.csv, samples/exampleNuggetRoomList.csv
From issue 182, removed a bunch of columns from the sample CSVs
=> Update csv samples to remove columns

samples/exampleBallysRoomList.csv, samples/exampleNuggetRoomList.csv
A small update to the previous pull request that removed tons of other columns, this finishes the job
=> Remove the guest restrictions column also

backend/reservations/ingest_models.py, frontend/src/components/admin.js, frontend/src/components/adminMetrics.js, frontend/src/pages/Admin.js
also fixes a bug in ingest-csv
this fixes #164
=> update admin on metrics refresh

backend/backend/settings.py, backend/reservations/checks.py, dev.env
* only run `find_drama` check on `deploy`
* ignore system checks we don't care about
=> some follow up checks details

backend/reservations/checks.py
throw an "info" message if rooms are reserved / held as placeholders without an actual name.
=> fixes and a new check for find_drama

Makefile, backend/config/roombaht-systemd.conf, backend/reservations/config.py, backend/reservations/management/commands/create_rooms.py, backend/reservations/management/commands/create_staff.py, backend/reservations/management/commands/send_onboarding.py, backend/reservations/views/admin.py, backend/scripts/roombaht-oob.sh, scripts/roombaht_ctl, scripts/roombaht_ctl-remote.sh
* pass url affecting config vars through
* option to resend staff onboarding email
* only render reports for hotels we care about
=> config, report, and dev ux fixes

backend/reservations/fixtures/test_rooms.yaml, backend/reservations/fixtures/test_users.yaml, backend/reservations/views/rooms.py, backend/tavern/test_room_swap.tavern.yml
beep boop this should match implicit user expectations
=> include placed rooms in full list of rooms

backend/reservations/checks.py, backend/reservations/helpers.py, backend/reservations/management/commands/room_edit.py, backend/reservations/views/admin.py
also clean up all `Guest` fields on transfer
=> room ticket cli edit

backend/reservations/management/commands/room_edit.py
=> support unassigning of placed rooms

LICENSE.md, terraform/auth.tf, terraform/db.tf, terraform/dns.tf, terraform/host.tf
* spin down prod env and db
* update license copyright
=> until next year
